version: '3.8'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
